### ISSUE TITLE
Paths and filenames of output libraries should match the official SDK

### ISSUE THREAD

**Issue by feilen** [jherico/OculusSDK#41]
I'm currently working with the Dolphin VR project, adding a small handful of things but mostly just making sure it works crossplatform. I've been using haagch's oculus-rift-sdk-jherico-git AUR package for ArchLinux for the libraries so far, which works great for the most part. However, with Dolphin, you're supposed to be able to run make over the SDK, copy LibOVR out of it into Externals/ in Dolphin, and have it automatically link against what it finds in there.

I'm okay right now since the linux implementation has been set up to use the above package, but for other distributions to work painlessly I need to be able to use the Externals as it is used in Windows. There are a couple problems though. When I link, currently I link against -lOculusSDK, while the official SDK outputs libovr.so. When the SDK is compiled, the official SDK put the object files into a subdirectory of LibOVR, while this puts it into OculusSDK/output. With all of this, I currently have a couple of options:

- Tell non-arch users trying to compile to grab the official version and compile it, and then go throughout Dolphin's CMake files and make it conditionally link against libovr.a or libOculusVR.a depending on what it finds

- Have users place OculusSDK instead of LibOVR in Externals/, breaking consistency with Windows (although ideally the SDK could be set up as a git module, but I'd have to get the other dolphin VR devs on board) and find/link against output/libOculusVR.a

A better case would simply to make this fork of the SDK output to identical directories/filenames as the official SDK, so that it's instantly compatible with it without needing manual adjustment. If nothing else, having a provided -DOFFICIAL_FILENAMES option switch would be enough to work with.

**Comment by feilen** [comment]
Sorry it took so long, but I've started some work on making it output more like the official SDK. Honestly, as long as the output library has the same name CMake should be able to find it in most cases. Ideally I'd still like to make the output paths the same.

**Comment by feilen** [comment]
By the way, where is the -O3 coming from? That's known to actually slow down most applications, unless it's something like cryptography. (huuge code size bloat)

**Comment by feilen** [comment]
Found it! CMake (for whatever reason) picks -O3 by default and has to be overridden... which most things do. Weird! Fixed and commited fix. I still have some things I want to clean up before I submit a pull request.

**Comment by jherico** [comment]
Cool find.  Thanks.
