### ISSUE TITLE
Trying to build a project in Eclipse - pthread_mutexattr_settype@@GLIBC_2.2.5

### ISSUE THREAD

**Issue by Nesh108** [jherico/OculusSDK#49]
Hello!

I am trying to run the OculusWorldDemo in c++, on Eclipse on Ubuntu 14.04.
I managed to link/include all the files I could but now I am getting the following error:

```./src/OculusRiftTest.o: undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5' OculusRiftTest	```

If I link the project to libOVR, I get the following error:

```//usr/local/lib/libOVR.a(OVR_CAPIShim.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'	OculusRiftTest	```

I often get the `@@GLIBC_2.2.5`. Is that common? How can I fix it?

**Comment by jherico** [comment]
This is not an official support forum for Oculus.  If you're having trouble building the examples packaged with the SDK, you should contact Oculus via their [forums](https://forums.oculus.com).
